# Generated by Django 4.0.3 on 2022-04-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRecords',
        ),
    ]
